[package]
name = "solve"
version = "0.1.0"
edition = "2021"

[dependencies]
auto_ops = "0.3.0"
clap = { version = "4.5.20", features = ["derive"] }
getrandom = "0.2.15"
hex = "0.4.3"
thiserror = "1.0.65"
